{% set name = "snowflake-telemetry-python" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 7cd6401a5ff0f4bfe99ac4c1854abf1317e0f195f5fca10f96645dd1706d87cd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39 and py>314]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=40.6.0
  run:
    - python
    - opentelemetry-api ==1.38.0
    - opentelemetry-sdk ==1.38.0

test:
  source_files:
    - tests
  imports:
    - snowflake
    - snowflake.telemetry
    - snowflake.telemetry.logs
    - snowflake.telemetry.trace
    - snowflake.telemetry.version
  commands:
    - pip check
    - pytest -v tests/test_basic.py
  requires:
    - pip
    - pytest

about:
  home: https://www.snowflake.com
  summary: Snowflake Telemetry for Python
  description: |
      snowflake-telemetry-python is a package that supports emitting
      telemetry data from Python UDFs, UDTFs, and Stored Procedures.
      This package is a stub for the full functionality when
      running in Snowflake.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://docs.snowflake.com/en/developer-guide/logging-tracing/tracing-python
  dev_url: https://github.com/snowflakedb/snowflake-telemetry-python

