{% set name = "snowflake-telemetry-python" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dde61307590a944b50745e199f3dfa3cc1b1966fd0f5aa030d8e905c81083460

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - opentelemetry-sdk 1.12.0
    - opentelemetry-api 1.12.0
    - opentelemetry-exporter-otlp 1.12.0

test:
  requires:
    - pip
  imports:
    - snowflake.telemetry
    - snowflake.telemetry.version
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowflake-telemetry-python
  summary: Snowflake Telemetry for Python
  description: |
      snowflake-telemetry-python is a package that supports emitting
      telemetry data from Python UDFs, UDTFs, and Stored Procedures.
      This package is a stub for the full functionality when
      running in Snowflake.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/snowflakedb/snowflake-telemetry-python/blob/main/README.md
  dev_url: https://github.com/snowflakedb/snowflake-telemetry-python


